# Infisocal Configuration
# See https://infisical.com/docs/cli/configuration for options

projectId: 4f27b05d-3ed6-4012-b8ac-af7b08e262d8

# Default environment when no --env flag is provided
# Options: dev, staging, prod
defaultEnv: dev

# Directory to write .env file (relative to project root)
# Infisical will inject secrets here
envFile: .env

# Environment-specific overrides
envs:
  dev:
    # Development environment uses default settings
    envFile: .env

  staging:
    # Staging environment
    envFile: .env.staging

  prod:
    # Production environment
    envFile: .env.production

# Secrets to fetch from Infisical
# Server-side secrets (not exposed to browser)
secrets:
  - DATABASE_URL
  - GOOGLE_CLIENT_EMAIL
  - GOOGLE_PRIVATE_KEY
  - GOOGLE_DRIVE_FOLDER_ID
  - RESEND_API_KEY
  - FROM_EMAIL

# Note: Client-side variables (NEXT_PUBLIC_*) should remain in your local .env
# as they are not sensitive and need to be bundled at build time.
